### ISSUE TITLE
Login Page: Navigation bar is a different color

### ISSUE THREAD

**Issue by dawa** [TummyOnTrack/TummyOnTrack#16]
Use the same color as the home page screen

**Comment by jessica-yzliu** [comment]
Profile page nav bar color is correct, do you want to say "Login and sign up page nav bar color"?

**Comment by dawa** [comment]
Yes. The one @tikekar and you were looking at. I wasn't looking :-D

**Comment by jessica-yzliu** [comment]
Onboarding navbar color fixed.
