### ISSUE TITLE
Voice Entry: Enhancements (awesome looking)

### ISSUE THREAD

**Issue by dawa** [TummyOnTrack/TummyOnTrack#20]
1. Tap to start button should be placed at the bottom of the page. 
2. Use a speaker icon instead of the default square button
3. Use the speaker bubbles for the conversation
4. Make the design (nav bar, background colors, bubble for the conversation) match the rest of the application
5. May be some sliding animation on bubbles (If possible and look good.)

**Comment by poojachow** [comment]
implemented
