### ISSUE TITLE
Taking photo on profile view crashes

### ISSUE THREAD

**Issue by tikekar** [TummyOnTrack/TummyOnTrack#27]
Note: I tested it on simulator and it crashed

**Comment by jessica-yzliu** [comment]
I think it does not work with simulator

**Comment by jessica-yzliu** [comment]
I tested with a real device, it worked.

**Comment by tikekar** [comment]
both camera and photos crashes from my phone

**Comment by tikekar** [comment]
Steps to reproduce- Open the add profile page, select the name so that keyboard opens. Now click on the camera or photos, it crashes

**Comment by tikekar** [comment]
Fixed it
