### ISSUE TITLE
Signup for passwords less than 6 characters does not work

### ISSUE THREAD

**Issue by tikekar** [TummyOnTrack/TummyOnTrack#3]
It should work. Or show the message to the user

**Comment by jessica-yzliu** [comment]
I added password length check and error message alert banner. 
What length do you want? 
Now the check is more than 6 letters.

**Comment by tikekar** [comment]
Any length password should work. For our app requirement the password does not need to be strict

**Comment by jessica-yzliu** [comment]
ok, password length check is now commented out. I didn't remove it in case if you need it later. We can do a final clean at the end.

**Comment by jessica-yzliu** [comment]
Firebase requires the password must be more than 6 letters. We cannot override password rules. So we have to keep the password length check.
