### ISSUE TITLE
After logout currentProfile from previous login is shown. 

### ISSUE THREAD

**Issue by tikekar** [TummyOnTrack/TummyOnTrack#35]
CurrentProfile from user defaults should get removed when logout clicked

**Comment by jessica-yzliu** [comment]
This issue is not caused by logout button. I think is class var currentProfile: TTProfile? inside TTProfile file,  "Set and Get " cannot set or get properly the current profile. Still trying to figure out

**Comment by tikekar** [comment]
fixed
