### ISSUE TITLE
Home Page: Chart click crashed

### ISSUE THREAD

**Issue by dawa** [TummyOnTrack/TummyOnTrack#39]
Login in with Sara user and switch to Peter's profile. Click on chart and it crashes.

<img width="1177" alt="screen shot 2017-05-06 at 9 16 58 pm" src="https://cloud.githubusercontent.com/assets/641287/25777888/983c95ce-32a1-11e7-9bbb-921dd6162109.png">

**Comment by tikekar** [comment]
I added a zero count check. Let me know if it still crashes again.
