### ISSUE TITLE
Decorate image page. The toy's copy should move, not the toy itself from the menu

### ISSUE THREAD

**Issue by tikekar** [TummyOnTrack/TummyOnTrack#50]

**Comment by tikekar** [comment]
Look into the smiley lab code

**Comment by poojachow** [comment]
in panGestureRecognizer.changed, need to change center of newlyCreatedReward instead of imageViewToPan(which is set to originalRewardImageView)

**Comment by dawa** [comment]
That causes the new image not to be draggable. Can you send me the link for your project if you got it to work or try it yourself?

**Comment by poojachow** [comment]
Gauri can you share the lab work? We had done it on your laptop

**Comment by dawa** [comment]
Done
