### ISSUE TITLE
Do points/rewards testing using new user and profile

### ISSUE THREAD

**Issue by tikekar** [TummyOnTrack/TummyOnTrack#52]
Create a new user and new profile. Add some voice over food entries. Now test the rewards to see if all the points there show up ok. I think there is some mismatch between unused points and weeklyPoints. Also Do not use weeklyPoints, instead use unused points to show in the points tab

**Comment by dawa** [comment]
New rewards don't shop up after purchasing a reward. They only show up after profile has been reloaded

**Comment by dawa** [comment]
Fixed.
