### ISSUE TITLE
Home Page: Top label constraint to prevent overlap with profile image

### ISSUE THREAD

**Issue by dawa** [TummyOnTrack/TummyOnTrack#53]
See picture below.

<img width="380" alt="screen shot 2017-05-10 at 8 12 16 am" src="https://cloud.githubusercontent.com/assets/641287/25906060/89cf6f20-3558-11e7-9f3c-3aa342999084.png">

**Comment by dawa** [comment]
Also goal point pie chart doesn't seem right when you have exceeded the goal for the week.

**Comment by dawa** [comment]
Message is wrong. It always says you are halfway through no matter how many points have been earned.

**Comment by tikekar** [comment]
fixed
