### ISSUE TITLE
Profiles: Create a child with same name pulls their wrong profile points

### ISSUE THREAD

**Issue by dawa** [TummyOnTrack/TummyOnTrack#56]
1. Create a profile in one account and do some activity like record food eaten today and buy rewards.
2. Logout a create a new profile with the same name as the previous profile.
3. You see the points and rewards for the other profile before you add any items.

**Comment by dawa** [comment]
@Yanze Pooja might have found the problem. Check with her.

**Comment by jessica-yzliu** [comment]
@dawa OK!

**Comment by poojachow** [comment]
Fixed. Please test
