### ISSUE TITLE
 After I bought one item in rewards shop, when I back to decorate my wall, I got full of items in my bag, is it normal?

### ISSUE THREAD

**Issue by jessica-yzliu** [TummyOnTrack/TummyOnTrack#57]

**Comment by dawa** [comment]
This is the same as #56  The profile loaded has the rewards for someone else

**Comment by tikekar** [comment]
No this is different. On backend i checked that the profile name is only for one profile. I can also reproduce it

**Comment by dawa** [comment]
@tikekar fixed this. Thanks!
