### ISSUE TITLE
Rewards page

### ISSUE THREAD

**Issue by tikekar** [TummyOnTrack/TummyOnTrack#58]
The rewards flow is not clear.
-When i select any reward, it gets expanded. Then I click "select", but nothing happens. 
-It should show selected as separate list. (collection view with sections, or show the selected ones under "You have XX points label" as an horizontal scrolling list.
-Also my unused points should change to reflect how many i have left to shop more.
-If any reward is expensive than I have points, then it should not be allowed to buy.

**Comment by dawa** [comment]
@tikekar fixed this.
